# Site settings
title: David's Mobile Auto Repair
description: > # this means to ignore newlines until "baseurl:"
  David's Mobile Auto Repair Service in North Augusta, SC. We do the job right, the first time, for the right price.
keywords: "Mechanic, Mobile, David Crook, Car, Auto, Automotive"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://davidsmobileautorepair.com" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
# paginate: 4
# paginate_path: "blog/page:num"

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - deploy.sh